### ISSUE TITLE
Reaching a 'Like' limit after 1000 likes

### ISSUE THREAD

**Issue by hermaster** [Amenly/onlyfans-scraper#102]
After exactly 1000 likes I start getting this message:
400 STATUS CODE: unable to like post at https://onlyfans.com...
I haven't yet waited long enough to know when I'm unblocked again. I can't like on the browser either.

**Comment by tetrahydr0** [comment]
You need to w8 24 hours - then you can do another 1000. It's OF limit

**Comment by Amenly** [comment]
Yup, you can only like around 1000 posts every 24 hours. There's nothing I can do about it unfortunately.
