### ISSUE TITLE
Why i only get free stuff and not paid / how can i tell which username to grab?

### ISSUE THREAD

**Issue by SkyVolticZ** [Amenly/onlyfans-scraper#107]
Hello,
can you tell me why i only can grab freestuff ?
I saw other can grab premium/paid .
Can you tell me where/how i can grab stuft im not following ?
Best Regards

**Comment by Amenly** [comment]
You need to be subscribed to the user to scrape their content; this doesn't bypass paywalls if that's what you're asking.
