### ISSUE TITLE
onlyfans-scraper

### ISSUE THREAD

**Issue by buffet69** [Amenly/onlyfans-scraper#11]
After installation I type onlyfans-scraper and it says command not found.

**Comment by Amenly** [comment]
Are you using Linux or Windows?

**Comment by buffet69** [comment]
Using Mac

**Comment by Amenly** [comment]
It definitely has something to do with your PATH because I'm able to run it on my Mac. Could you tell me which version you're using? Catalina? Big Sur?

**Comment by buffet69** [comment]
Big Sur

**Comment by Amenly** [comment]
If you open your Terminal application, do you see "zsh" in the window title? Kind of like in here:

![zsh-mac-terminal](https://user-images.githubusercontent.com/60410674/116842727-25600200-aba3-11eb-9058-5a7abae28442.jpg)

If you do see "zsh", make sure you're in your home directory. To make sure you're in your home directory, type the following in your terminal:

```
cd ~/
```

Now that you're in your home directory, type the following in your terminal:

```
open -e .zshrc
```

This will open your `.zshrc` file in the TextEdit app (or if you changed it to another text editor). Once it opens, go back to your terminal and type in the following:

```
which python3
```

This will print the path to your version of python3. Mine looks like this: `/Library/Frameworks/Python.framework/Versions/3.9/bin/python3`

The part we want is everything before the last forward slash: `/Library/Frameworks/Python.framework/Versions/3.9/bin`

Copy that part (make sure `bin` is in it) and now go back to the `.zshrc` file and somewhere in there, type the following:

```
# Setting PATH for Python 3.9
PATH="/Library/Frameworks/Python.framework/Versions/3.9/bin:${PATH}"
export PATH
```

You should (hopefully) be able to run it now.

**Comment by buffet69** [comment]
I don’t have a .zshrc file.  bash is the default.
/usr/bin/python3 is where python is located.

Been a long time since I have tried to do command line things.  Sorry for being so green.

**Comment by Amenly** [comment]
No worries. Actually, since you're using bash, the instructions shouldn't be too different. 

Instead of doing:

```
open -e .zshrc
```

Do this instead:

```
open -e .bash_profile
```

And enter the following in your bash file:

```
# Setting PATH for Python 3
PATH="/usr/bin:${PATH}"
export PATH
```

**Comment by buffet69** [comment]
<img width="383" alt="image" src="https://user-images.githubusercontent.com/83567667/116844681-9d74fa80-ab98-11eb-9607-50f9aa78b871.png">

**Comment by buffet69** [comment]
Might the install be putting it in a different location because I didn't have the PATH set when I did the install?

**Comment by Gixxa** [comment]
I have the same issue but I'm using zsh.

```
# Setting PATH for Python 3
PATH="/usr/bin:${PATH}"
export PATH
```

The default Python 3 for Big Sur 11.3 is 3.8.2 maybe it's too old? If I try `python3 onlyfans-scraper` I get:

`/Applications/Xcode.app/Contents/Developer/usr/bin/python3: can't open file 'onlyfans-scraper': [Errno 2] No such file or directory`

pwd is:

`/Users/*username*/Library/Python/3.8/lib/python/site-packages`

On this machine no python3 application as ever been installed so this scraper is the only app running.

**Comment by Gixxa** [comment]
> Might the install be putting it in a different location because I didn't have the PATH set when I did the install?

That was the issue for me.

Here is what I did (note as I've said no other python apps are installed on my machine so double check in your case):

`pip3 freeze > requirements.txt`

`pip3 uninstall -r requirements.txt`

`pip3 install onlyfans-scraper`

`onlyfans-scraper` --> entered all the details

**Comment by Amenly** [comment]
@buffet69 Maybe the problem is what you entered for your path. `onlyfans-scraper` as a command line script is going to be in your `bin` for your installation of python. So for you, it's probably going to be in `/usr/bin`. 

However, in your screenshot, you set the path as `/usr/bin/python3`

You can try to confirm this by looking through in that path. Go to Finder, press CMD + Shift + G and type in `/usr/bin` and check if you see a unix executable for `onlyfans-scraper`

Maybe [this page](https://unix.stackexchange.com/questions/240037/why-did-pip-install-a-package-into-local-bin) can help too?
