### ISSUE TITLE
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://onlyfans.com/api2/v2/users/me'

### ISSUE THREAD

**Issue by IAmOrion** [Amenly/onlyfans-scraper#150]
This scraper USED to work fine but now the 'status' always says DOWN and I always get this error
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://onlyfans.com/api2/v2/users/me'
It strangely logs me out of OF too after trying this. I re-log in via browser, I update the auth.json with the correct values but it would appear this no longer works

**Comment by HTP-BWA** [comment]
@IAmOrion  Any advice on how you overcame this? I am currently dealing with the same issue

**Comment by IAmOrion** [comment]
Make sure the Browser version is identical to whatever browser you're using.  That was the cause of my issue
