### ISSUE TITLE
'onlyfans-scraper' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by NotoriousFan** [Amenly/onlyfans-scraper#19]
![onlyf](https://user-images.githubusercontent.com/79220713/117346925-66dc0000-ae76-11eb-9711-e4870f71f6e6.png)

(windows) Am I missing something? I can use DigitalCriminal without any issues

**Comment by Amenly** [comment]
It's because you don't have the path to the scripts directory added to your PATH. 

Enter this in PowerShell:

```
Get-Command python
```

Then copy the path, get rid of everything after the last backslash, and add 'Scripts' to the path. Then add that to your environment variables.

**Comment by NotoriousFan** [comment]
Seems like I had too many versions of python. I ended up redoing the path for both python and the scripts. Now it's working perfectly. Thank you.
