### ISSUE TITLE
400 error message

### ISSUE THREAD

**Issue by mixan21** [Amenly/onlyfans-scraper#29]
Hello can i know what error happen that i get? i got this error after performing an update to the latest version. Thank you.

Traceback (most recent call last):
  File "/home/mixan/.local/bin/onlyfans-scraper", line 8, in <module>
    sys.exit(main())
  File "/home/mixan/.local/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 321, in main
    process_prompts()
  File "/home/mixan/.local/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 268, in process_prompts
    loop()
  File "/home/mixan/.local/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 209, in process_prompts
    subscribe_count = process_me(headers)
  File "/home/mixan/.local/lib/python3.9/site-packages/onlyfans_scraper/scraper.py", line 189, in process_me
    my_profile = me.scrape_user(headers)
  File "/home/mixan/.local/lib/python3.9/site-packages/onlyfans_scraper/api/me.py", line 26, in scrape_user
    r.raise_for_status()
  File "/home/mixan/.local/lib/python3.9/site-packages/httpx/_models.py", line 1105, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 400 Client Error: Bad Request for url: https://onlyfans.com/api2/v2/users/me
For more information check: https://httpstatuses.com/400

**Comment by Amenly** [comment]
They changed their auth again. Upgrade to `1.6.0`:

```
pip install --upgrade onlyfans-scraper
```

However, I'm going to release another version of the program to use the same endpoint as DC so you won't have to update the script whenever OF changes their auth.

**Comment by Amenly** [comment]
I just released `1.7.0`. With this one, you will no longer have to wait for me to update the program for it to work and you won't have to keep upgrading it.

**Comment by mixan21** [comment]
> I just released `1.7.0`. With this one, you will no longer have to wait for me to update the program for it to work and you won't have to keep upgrading it.

Can i know how you make that happen since iam interesting in this feature you make for the release. Looks i can learn something with this concept. 

Ps. The script can be used and already be tested. Thank you for your hard work to make it happen 🙏

**Comment by Amenly** [comment]
@mixan21 It's nothing special tbh, I'm just using the same endpoint that DC created [here](https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json). The program will read the JSON and update the `sign` parameters. Unfortunately, this script will now rely on him updating the endpoint which means if his script doesn't work, neither will ours. But I think this makes it much more convenient in the long run.

**Comment by mixan21** [comment]
> @mixan21 It's nothing special tbh, I'm just using the same endpoint that DC created [here](https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json). The program will read the JSON and update the `sign` parameters. Unfortunately, this script will now rely on him updating the endpoint which means if his script doesn't work, neither will ours. But I think this makes it much more convenient in the long run.

Since I am a network security student but weak with programming this looks interesting. I think python language is interesting and the script based on python is fun. I think it worth to learn python in the future. Thank you for the explanation and help you provided! 👍
