### ISSUE TITLE
Issue resulting in 400 Client Error

### ISSUE THREAD

**Issue by cpgifford** [Amenly/onlyfans-scraper#32]
Was working fine all day then all the sudden I get this error after retrying a download of a profile because of an error

<pre><font color="#5F87AF">?</font><b> Choose one of the following options: </b><font color="#FFAF00"><b> Print a list of my subscriptions</b></font>
Traceback (most recent call last):
  File &quot;/home/user/.local/bin/onlyfans-scraper&quot;, line 8, in &lt;module&gt;
    sys.exit(main())
  File &quot;/home/user/.local/lib/python3.8/site-packages/onlyfans_scraper/scraper.py&quot;, line 321, in main
    process_prompts()
  File &quot;/home/user/.local/lib/python3.8/site-packages/onlyfans_scraper/scraper.py&quot;, line 209, in process_prompts
    subscribe_count = process_me(headers)
  File &quot;/home/user/.local/lib/python3.8/site-packages/onlyfans_scraper/scraper.py&quot;, line 189, in process_me
    my_profile = me.scrape_user(headers)
  File &quot;/home/user/.local/lib/python3.8/site-packages/onlyfans_scraper/api/me.py&quot;, line 26, in scrape_user
    r.raise_for_status()
  File &quot;/home/user/.local/lib/python3.8/site-packages/httpx/_models.py&quot;, line 1402, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 400 Client Error: Bad Request for url: https://onlyfans.com/api2/v2/users/me
For more information check: https://httpstatuses.com/400</pre>

**Comment by cpgifford** [comment]
I have the latest OF-Scraper installed, in fact I installed it yesterday

**Comment by tetrahydr0** [comment]
This is same error that was before v1.7.2. Probably have to w8 till they done changing site mechanics

**Comment by Amenly** [comment]
Yeah it's down. They changed how their `sign` is created again. This program uses the same method that DC uses to update the `sign` on the spot and, just as I expected, DC's program isn't working for me either atm. 

We pretty much have to wait for him to update the endpoint. You won't have to reinstall anything.

**Comment by itsdavee316** [comment]
Was working, I seem to have lost access again. Same error. Was working earlier and now, nothing.

**Comment by Amenly** [comment]
@itsdavee316 Is it still broken for you? Because on my end, it's working fine atm

**Comment by Garcarius** [comment]
> @itsdavee316 Is it still broken for you? Because on my end, it's working fine atm

![image](https://user-images.githubusercontent.com/39957800/119137735-c3a6f100-ba06-11eb-980b-0c2a057736b4.png)

i have the same problem

**Comment by Amenly** [comment]
I'm going to close this because this sort of issue is going to come and (hopefully) go every now and then. At the moment, everything's working fine.
