### ISSUE TITLE
KeyError: 'x-bc' after update

### ISSUE THREAD

**Issue by supposedcash** [Amenly/onlyfans-scraper#54]
Hi there,

I was running into some HTTP 400 errors after updating my auth.json file, so I figured I would upgrade the onlyfans-scraper as maybe I was out of date. I went from version 0.3.2 to 1.7.2, which gave me a different set of issues.

It appears to have made the main_profile fine, but after that it can't even run the package. I get the following output:

```Using profile: main_profile
Traceback (most recent call last):
  File "/home/me/.local/bin/onlyfans-scraper", line 8, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.8/site-packages/onlyfans_scraper/scraper.py", line 321, in main
    process_prompts()
  File "/home/me/.local/lib/python3.8/site-packages/onlyfans_scraper/scraper.py", line 199, in process_prompts
    headers = auth.make_headers(auth.read_auth())
  File "/home/me/.local/lib/python3.8/site-packages/onlyfans_scraper/utils/auth.py", line 91, in make_headers
    'x-bc': auth['auth']['x-bc'],
KeyError: 'x-bc'
```

To be sure, I did have to finagle it to even get this installed and running with Python 3.8, hence the file path. I'm on Ubuntu 18.04, which I upgraded from Ubuntu 16.04, which if I recall correctly comes with both python 2 and 3.

I did try to uninstall and reinstall the package, but I get the same error. I get the feeling that the best course of action might be "back everything up and reinstall."

**Comment by Amenly** [comment]
Yeah that version's been outdated for quite some time. You should clean out the previous `onlyfans-scraper` directory (located at: `~/.config/onlyfans-scraper`)

If you want, you could probably save the previous `models.db` file before clearing out the directory. Then, after rerunning the program, put it back in the `main_profile` directory.

**Comment by supposedcash** [comment]
That did the trick. There must've been some funk leftover when I upgraded or something. I didn't think to read the rest of the readme to learn about the x-bc value. Thanks for suffering a fool like me, I appreciate it.
