### ISSUE TITLE
File

### ISSUE THREAD

**Issue by watsonlowe99** [Amenly/onlyfans-scraper#78]
Im on Mac and I successfully scrapped someone onlyfans where can I find the information that I just scrapped

**Comment by Amenly** [comment]
It should be in the same directory you were in when you ran it in Terminal. There's a good chance the path is `./modelusername`

Just replace `modelusername` with the name of the model whose content you scraped.

If you open Terminal and enter the following command:

```
open ./modelusername
```

It should open the folder.
